package com.neobe.bto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "ContextoExecucaoProcesso")
public class ContextoExecucaoProcesso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CONTEXTOEXECUCAOPROCESSO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "CONTEXTOEXECUCAOPROCESSO_ID_SEQ", name = "CONTEXTOEXECUCAOPROCESSO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Guia de solicitação")
	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private com.neobe.bto.GuiaSolicitacao guiaSolicitacao;

	@org.kie.api.definition.type.Label(value = "teste")
	private java.lang.String teste;

	public ContextoExecucaoProcesso() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public com.neobe.bto.GuiaSolicitacao getGuiaSolicitacao() {
		return this.guiaSolicitacao;
	}

	public void setGuiaSolicitacao(com.neobe.bto.GuiaSolicitacao guiaSolicitacao) {
		this.guiaSolicitacao = guiaSolicitacao;
	}

	public java.lang.String getTeste() {
		return this.teste;
	}

	public void setTeste(java.lang.String teste) {
		this.teste = teste;
	}

	public ContextoExecucaoProcesso(java.lang.Long id,
			com.neobe.bto.GuiaSolicitacao guiaSolicitacao,
			java.lang.String teste) {
		this.id = id;
		this.guiaSolicitacao = guiaSolicitacao;
		this.teste = teste;
	}

}