package com.neobe.bto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Teste")
public class Teste implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("teste")
	private java.lang.String teste;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TESTE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TESTE_ID_SEQ", name = "TESTE_ID_GENERATOR")
	private java.lang.Long id;

	public Teste() {
	}

	public java.lang.String getTeste() {
		return this.teste;
	}

	public void setTeste(java.lang.String teste) {
		this.teste = teste;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Teste(java.lang.String teste, java.lang.Long id) {
		this.teste = teste;
		this.id = id;
	}

}