package com.neobe.bto;

import com.neobe.bto.ContextoExecucaoProcesso;
import com.neobe.bto.Beneficiario;
import com.neobe.bto.Negativa;
import com.neobe.bto.GuiaSolicitacao;
import com.neobe.bto.Solicitante;


import java.util.ArrayList;  
import java.util.List;
import java.io.Serializable;


rule "1214 - Credenciado não habilitado a realizar o procedimento"
    enabled true
    ruleflow-group "elegibilidade_beneficiario"
    dialect "mvel"
    when
        $contexto: ContextoExecucaoProcesso()
        $guiaSolicitacao: GuiaSolicitacao() from $contexto.guiaSolicitacao
        $solicitante: Solicitante(afastado == true || bloqueado == true) from $guiaSolicitacao.solicitante
    then
        $negativas = $guiaSolicitacao.getNegativas();
        $nova = new Negativa(1214,'1214', 'Credenciado não habilitado a realizar o procedimento');
        $negativas.add($nova);
        $guiaSolicitacao.setNegativas($negativas);
        insert($negativas);
end